name: ci

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn lint:check

  test:
    strategy:
      matrix:
        node-version: [16, 17, 18, 19, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn test

  build-example-next-contentlayer-example:
    strategy:
      matrix:
        node-version: [17, 18, 19, 20] # `app` dir requires 17+
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/next-contentlayer-example

  build-example-next-rsc-dynamic-example:
    strategy:
      matrix:
        node-version: [17, 18, 19, 20] # `app` dir requires 17+
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/next-rsc-dynamic

  build-example-next-images-example:
    strategy:
      matrix:
        node-version: [17, 18, 19, 20] # `app` dir requires 17+
        # TODO re-enable windows
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/next-images

  build-example-node-script:
    strategy:
      matrix:
        node-version: [16, 17, 18, 19, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn start
        working-directory: examples/node-script

  build-example-node-script-mdx:
    strategy:
      matrix:
        node-version: [16, 17, 18, 19, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn start
        working-directory: examples/node-script-mdx

  build-example-node-script-remote-content:
    strategy:
      matrix:
        node-version: [16, 17, 18, 19, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn start
        working-directory: examples/node-script-remote-content
